// 全部 18 关的元数据（取自《汉字解谜 · 关卡设计 v4》）。
// template 里的 “＿” 表示一个填空格，按出现顺序对应 answers。
// implemented=true 表示该关已写好交互逻辑（registry.js 里有对应模块）。

export const CHAPTERS = [
  { id: 1, title: '第一章 · 基础', range: [1, 4] },
  { id: 2, title: '第二章 · 进阶', range: [5, 9] },
  { id: 3, title: '第三章 · 文化梗 / 多字填空', range: [10, 14] },
  { id: 4, title: '第四章 · 高阶', range: [15, 18] },
];

export const LEVELS = [
  {
    id: 1,
    chapter: 1,
    title: '水能载舟',
    template: '＿能载舟',
    answers: ['水'],
    materials: ['火', '冰'],
    mechanic: '熔化 · 形意双关',
    difficulty: 1,
    solution: '把「火」拖到「冰」旁边，冰左侧的「冫」被烤化，整字变成「水」。',
    implemented: true,
  },
  {
    id: 2,
    chapter: 1,
    title: '歪打正着',
    template: '＿打正着',
    answers: ['歪'],
    materials: ['正'],
    mechanic: '旋转 · 形即意',
    difficulty: 1,
    solution: '抓住「正」往一边拧 / 扳斜，它就变成了「歪」。',
    implemented: true,
  },
  {
    id: 3,
    chapter: 1,
    title: '更上一层楼',
    template: '更＿一层楼',
    answers: ['上'],
    materials: ['下'],
    mechanic: '翻转 · 形 + 反义',
    difficulty: 1,
    solution: '把「下」上下翻转，就成了「上」。',
    implemented: true,
  },
  {
    id: 4,
    chapter: 1,
    title: '明月几时有',
    template: '＿月几时有',
    answers: ['明'],
    materials: ['口', '口', '月'],
    mechanic: '拼合（两步）· 形',
    difficulty: 2,
    solution: '两个「口」上下拼成「日」；再把「日」和「月」合成「明」。',
    implemented: true,
  },
  {
    id: 5,
    chapter: 2,
    title: '口若悬河',
    template: '口若悬＿',
    answers: ['河'],
    materials: ['很多个「水」'],
    mechanic: '排列成形 · 意',
    difficulty: 2,
    solution: '把一堆「水」首尾排成一道竖线，连成流动的水流，汇成「河」。',
    implemented: true,
  },
  {
    id: 6,
    chapter: 2,
    title: '移花接木',
    template: '移花接＿',
    answers: ['木'],
    materials: ['森', '斧'],
    mechanic: '斧砍 / 拆字（两步）· 形 + 量变',
    difficulty: 2,
    solution: '用「斧」碰「森」砍成「林」，再碰一下砍成「木」。',
    implemented: true,
  },
  {
    id: 7,
    chapter: 2,
    title: '鲜为人知',
    template: '＿为人知',
    answers: ['鲜'],
    materials: ['网', '很多个「水」', '羊'],
    mechanic: '捞取 + 合成（两步）· 意 + 会意',
    difficulty: 2,
    solution: '用「网」在水里捞出「鱼」；「鱼」和「羊」合成「鲜」（读 xiǎn）。',
    implemented: true,
  },
  {
    id: 8,
    chapter: 2,
    title: '枯木逢春',
    template: '枯＿逢春',
    answers: ['木'],
    materials: ['种子', '水', '阳光（日）'],
    mechanic: '生长链（两步）· 意',
    difficulty: 2,
    solution: '种子浇水 + 晒太阳发芽成「苗」；再浇一次水长成「木」。',
    implemented: true,
  },
  {
    id: 9,
    chapter: 2,
    title: '淡泊名利',
    template: '＿泊名利',
    answers: ['淡'],
    materials: ['火', '火', '水'],
    mechanic: '合成 + 浇灭（两步）· 形意双关',
    difficulty: 3,
    solution: '两个「火」叠成「炎」；再把「水」浇上去，「炎」被冲淡成「淡」。',
    implemented: true,
  },
  {
    id: 10,
    chapter: 3,
    title: '风吹草低见牛羊',
    template: '风吹草低见＿＿',
    answers: ['牛', '羊'],
    materials: ['风', '草'],
    mechanic: '吹拂显物 · 文化（多字填空）',
    difficulty: 3,
    solution: '把「风」吹向「草」，草伏低，露出藏着的「牛」和「羊」，分别填入两个空。',
    implemented: true,
  },
  {
    id: 11,
    chapter: 3,
    title: '虎头蛇尾',
    template: '＿头蛇尾',
    answers: ['虎'],
    materials: ['人', '人', '人'],
    mechanic: '众口 / 断言成真 · 文化',
    difficulty: 3,
    solution: '三个「人」聚到一起一口咬定有虎——三人成虎，凭空“说”出一只「虎」。',
    implemented: true,
  },
  {
    id: 12,
    chapter: 3,
    title: '一马当先',
    template: '一＿当先',
    answers: ['马'],
    materials: ['鹿', '指', '赵高'],
    mechanic: '合成动作 + 指认 / 改名（两步）· 文化',
    difficulty: 3,
    solution: '「赵高」+「指」合成“指认”这个动作；施加到「鹿」上，硬说是马，「鹿」变「马」。',
    implemented: true,
  },
  {
    id: 13,
    chapter: 3,
    title: '笔走龙蛇',
    template: '笔走龙＿',
    answers: ['蛇'],
    materials: ['弓', '一杯酒'],
    mechanic: '倒影 · 文化',
    difficulty: 3,
    solution: '把「弓」举到酒杯上方，倒影落进酒里，浮出一条「蛇」的影子，捞出「蛇」。',
    implemented: true,
  },
  {
    id: 14,
    chapter: 3,
    title: '雪中送炭',
    template: '雪中送＿',
    answers: ['炭'],
    materials: ['斧', '森', '火'],
    mechanic: '斧砍 + 火烧（三步）· 意',
    difficulty: 4,
    solution: '用「斧」把「森」砍成「林」再砍成「木」；最后用「火」把「木」烧成「炭」。',
    implemented: true,
  },
  {
    id: 15,
    chapter: 4,
    title: '一针见血',
    template: '一＿见血',
    answers: ['针'],
    materials: ['铁杵', '磨刀石（磨）'],
    mechanic: '摩擦（持续 / 时间）· 文化',
    difficulty: 4,
    solution: '拿「磨」反复摩擦「铁杵」，磨很多下，杵越磨越细，最后变成「针」。',
    implemented: true,
  },
  {
    id: 16,
    chapter: 4,
    title: '动如脱兔',
    template: '动如脱＿',
    answers: ['兔'],
    materials: ['树桩（株）'],
    mechanic: '放置 + 等待（时间）· 文化',
    difficulty: 4,
    solution: '把「树桩」摆到路边然后等待；过一会儿一只兔子撞上树桩，得到「兔」。',
    implemented: true,
  },
  {
    id: 17,
    chapter: 4,
    title: '杯水车薪',
    template: '杯水车＿',
    answers: ['薪'],
    materials: ['锅（釜）+ 柴（薪）', '一杯水（诱饵）'],
    mechanic: '抽薪 / 釜底（横向思维）· 文化',
    difficulty: 4,
    solution: '别浇那杯水（压不住）。把锅底下的「柴（薪）」抽出来——火灭，拿到「薪」。',
    implemented: true,
  },
  {
    id: 18,
    chapter: 4,
    title: '打草惊蛇',
    template: '打草惊＿',
    answers: ['蛇'],
    materials: ['蛇', '足'],
    mechanic: '克制（陷阱）· 文化',
    difficulty: 4,
    solution: '直接把「蛇」填进去。千万别给蛇添「足」——添了足蛇就长腿溜走，得重来。',
    implemented: true,
  },
];

export const getLevel = (id) => LEVELS.find((lvl) => lvl.id === id);
